- hosts: localhost
  tasks:
    - name: Read input
      set_fact:
        input: "{{ lookup('file', 'input').splitlines() }}"
    - name: Find items which sum to 2020
      set_fact:
        answer: "{{ item }}"
      with_community.general.cartesian:
        - "{{ input | map('int') | list }}"
        - "{{ input | map('int') | list }}"
      when: item[0] + item[1] == 2020
    - name: Display output
      debug: msg="{{ answer }}"
